// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Ace.Crm.Acceptance.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ContactManagementFeature : object, Xunit.IClassFixture<ContactManagementFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Contact management", ("  As a small company managing relationships with contacts and companies\n  I want " +
                "to record contacts, their companies, and interactions with them\n  So that follow" +
                "-ups never get lost"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ContactManagement.feature"
#line hidden
        
        public ContactManagementFeature(ContactManagementFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Recording a contact with only a first name is accepted")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Recording a contact with only a first name is accepted")]
        public async System.Threading.Tasks.Task RecordingAContactWithOnlyAFirstNameIsAccepted()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Recording a contact with only a first name is accepted", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
      await testRunner.GivenAsync("no contacts have been recorded yet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
      await testRunner.WhenAsync("I record a contact with first name \"Ada\" and no last name", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
      await testRunner.ThenAsync("the contact is accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Recording a contact with no name at all is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Recording a contact with no name at all is rejected")]
        public async System.Threading.Tasks.Task RecordingAContactWithNoNameAtAllIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Recording a contact with no name at all is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
      await testRunner.GivenAsync("no contacts have been recorded yet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
      await testRunner.WhenAsync("I record a contact with no first name and no last name", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
      await testRunner.ThenAsync("the contact is rejected with a reason mentioning \"name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registering a new company with a unique name succeeds")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Registering a new company with a unique name succeeds")]
        public async System.Threading.Tasks.Task RegisteringANewCompanyWithAUniqueNameSucceeds()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registering a new company with a unique name succeeds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
      await testRunner.GivenAsync("no companies have been registered yet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
      await testRunner.WhenAsync("I register a company named \"Acestus Infrastructure\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
      await testRunner.ThenAsync("the company is accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registering a company with a name already in use is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Registering a company with a name already in use is rejected")]
        public async System.Threading.Tasks.Task RegisteringACompanyWithANameAlreadyInUseIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registering a company with a name already in use is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
      await testRunner.GivenAsync("a company named \"Acestus Infrastructure\" is already registered", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
      await testRunner.WhenAsync("I register a company named \"Acestus Infrastructure\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
      await testRunner.ThenAsync("the company is rejected with a reason mentioning \"already exists\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Logging a call against an existing contact succeeds")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Logging a call against an existing contact succeeds")]
        public async System.Threading.Tasks.Task LoggingACallAgainstAnExistingContactSucceeds()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logging a call against an existing contact succeeds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
      await testRunner.GivenAsync("a contact named \"Ada Lovelace\" has been recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
      await testRunner.WhenAsync("I log a \"call\" interaction against \"Ada Lovelace\" today", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
      await testRunner.ThenAsync("the interaction is accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
      await testRunner.AndAsync("\"Ada Lovelace\" has 1 recorded interaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Logging an interaction against a contact that does not exist is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Logging an interaction against a contact that does not exist is rejected")]
        public async System.Threading.Tasks.Task LoggingAnInteractionAgainstAContactThatDoesNotExistIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logging an interaction against a contact that does not exist is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
      await testRunner.GivenAsync("no contacts have been recorded yet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
      await testRunner.WhenAsync("I log a \"call\" interaction against \"Ghost Contact\" today", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
      await testRunner.ThenAsync("the interaction is rejected with a reason mentioning \"does not exist\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Logging an interaction with an unrecognized type is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Logging an interaction with an unrecognized type is rejected")]
        public async System.Threading.Tasks.Task LoggingAnInteractionWithAnUnrecognizedTypeIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logging an interaction with an unrecognized type is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 44
      await testRunner.GivenAsync("a contact named \"Ada Lovelace\" has been recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
      await testRunner.WhenAsync("I log a \"carrier-pigeon\" interaction against \"Ada Lovelace\" today", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
      await testRunner.ThenAsync("the interaction is rejected with a reason mentioning \"not one of\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Scheduling a follow-up after the interaction date succeeds")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Scheduling a follow-up after the interaction date succeeds")]
        public async System.Threading.Tasks.Task SchedulingAFollow_UpAfterTheInteractionDateSucceeds()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Scheduling a follow-up after the interaction date succeeds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
      await testRunner.GivenAsync("a contact named \"Ada Lovelace\" has been recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
      await testRunner.WhenAsync(("I log a \"email\" interaction against \"Ada Lovelace\" today with a follow-up 3 days " +
                        "later"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
      await testRunner.ThenAsync("the interaction is accepted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Scheduling a follow-up before the interaction date is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Contact management")]
        [Xunit.TraitAttribute("Description", "Scheduling a follow-up before the interaction date is rejected")]
        public async System.Threading.Tasks.Task SchedulingAFollow_UpBeforeTheInteractionDateIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Scheduling a follow-up before the interaction date is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
      await testRunner.GivenAsync("a contact named \"Ada Lovelace\" has been recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
      await testRunner.WhenAsync(("I log a \"email\" interaction against \"Ada Lovelace\" today with a follow-up 3 days " +
                        "earlier"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
      await testRunner.ThenAsync("the interaction is rejected with a reason mentioning \"after\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ContactManagementFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ContactManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
