#!/usr/bin/env python3
"""Publish planner/outbox/*.md to Confluence under WWeeks → WWeeks Outbox.

First run bootstraps the parent pages "WWeeks" and "WWeeks Outbox" in the IPM
space, then creates one child page per outbox file. Subsequent runs update the
existing pages in place. Page IDs are persisted in
planner/outbox/.confluence-pages.json so the script is idempotent.

After publishing, planner/outbox/INDEX.md is regenerated with the Confluence
URL for each stakeholder file — share those URLs directly with the people you
are waiting on.

Usage:
    # First run — bootstraps parents
    python3 scripts/outbox_publish.py

    # Use an existing WWeeks parent page instead of creating one
    python3 scripts/outbox_publish.py --wweeks-parent-id 1234567

    # Show what would happen without calling Confluence
    python3 scripts/outbox_publish.py --dry-run

Requires CONFLUENCE_EMAIL and WWEEKS_CONFLUENCE_API_TOKEN in .env.
"""

import argparse
import importlib.util
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from lib.errors import fail, CONFLUENCE_COMMON_CAUSES

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTBOX_DIR = REPO_ROOT / "planner" / "outbox"
MAPPING_FILE = OUTBOX_DIR / ".confluence-pages.json"
INDEX_FILE = OUTBOX_DIR / "INDEX.md"
SPACE_KEY = "IPM"
SITE = "https://<YOUR_ATLASSIAN>.atlassian.net"

# Reuse the ADF converter + API helpers from create-confluence-page.py
_CCP_PATH = Path(__file__).parent / "create-confluence-page.py"
_spec = importlib.util.spec_from_file_location("ccp", _CCP_PATH)
ccp = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ccp)


# ── Mapping persistence ────────────────────────────────────────────────────────


def load_mapping():
    if MAPPING_FILE.exists():
        return json.loads(MAPPING_FILE.read_text(encoding="utf-8"))
    return {"_parents": {}, "files": {}}


def save_mapping(mapping):
    MAPPING_FILE.write_text(
        json.dumps(mapping, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


# ── Confluence helpers ─────────────────────────────────────────────────────────


def page_url(page_id, title):
    safe = title.replace(" ", "+")
    return f"{SITE}/wiki/spaces/{SPACE_KEY}/pages/{page_id}/{safe}"


def fetch_page(page_id):
    """Return page dict or None if it 404s."""
    try:
        return ccp.api_request("GET", f"content/{page_id}?expand=version")
    except SystemExit:
        return None


def make_adf(markdown_text):
    return json.dumps(ccp.md_to_adf(markdown_text), ensure_ascii=False)


def create_page(title, parent_id, body_markdown):
    payload = {
        "type": "page",
        "title": title,
        "space": {"key": SPACE_KEY},
        "ancestors": [{"id": parent_id}],
        "body": {
            "atlas_doc_format": {
                "value": make_adf(body_markdown),
                "representation": "atlas_doc_format",
            }
        },
    }
    return ccp.api_request("POST", "content", payload)


def update_page(page_id, title, body_markdown):
    current = fetch_page(page_id)
    if not current:
        return None
    new_version = current["version"]["number"] + 1
    payload = {
        "type": "page",
        "title": title,
        "version": {"number": new_version},
        "body": {
            "atlas_doc_format": {
                "value": make_adf(body_markdown),
                "representation": "atlas_doc_format",
            }
        },
    }
    return ccp.api_request("PUT", f"content/{page_id}", payload)


# ── Parent page bootstrap ──────────────────────────────────────────────────────


WWEEKS_INTRO = """# WWeeks

Personal workspace for <YOUR_NAME>. Child pages are auto-published from the
`projects` repository.

## Sections

- **WWeeks Outbox** — Per-stakeholder follow-up cards. Each child page lists
  every Jira ticket I'm waiting on that person (or external group) for. Share
  the relevant child URL with the stakeholder when chasing a response.
"""

OUTBOX_INTRO = """# WWeeks Outbox

Per-stakeholder follow-up board. Each child page mirrors one file under
`planner/outbox/` in the `projects` repository and is regenerated by
`scripts/outbox_publish.py`.

- **Person pages** (e.g. *<APPROVER_NAME>*, *Andrew Fuqua*) list every ticket I
  am currently waiting on that person for.
- **Bucket pages** start with an underscore — `_Vendor`, `_Code Review`,
  `_External Ticket`, `_Compliance`, etc. — for waits that aren't owned by a
  single person.
- Cards follow a newspaper-lede format: short paragraph on *what* and *why*,
  then *Status* / *Next* / *Links* / *Linked issues*.

To share a card with a stakeholder, copy the URL of their page from the child
list below or from `planner/outbox/INDEX.md` in the repo.

_Do not edit pages here — changes are overwritten on the next publish._
"""


def ensure_parent(mapping, key, title, body_markdown, parent_id=None, dry_run=False):
    """Ensure a parent page with stored ID exists; create if missing."""
    existing_id = mapping["_parents"].get(key)
    if existing_id:
        # Verify it still exists
        page = fetch_page(existing_id)
        if page:
            print(f"📂 {title}: existing page {existing_id} (v{page['version']['number']})")
            return existing_id
        print(f"⚠️  {title}: stored ID {existing_id} no longer exists — recreating")
        mapping["_parents"].pop(key, None)

    if dry_run:
        print(f"📂 {title}: [dry-run] would create under parent={parent_id}")
        return f"<new-{key}-id>"

    print(f"📂 {title}: creating...")
    res = create_page(title, parent_id, body_markdown) if parent_id else _create_root(title, body_markdown)
    new_id = res["id"]
    mapping["_parents"][key] = new_id
    print(f"   ✓ created → {new_id}")
    return new_id


def _create_root(title, body_markdown):
    """Create a top-level page (no ancestors)."""
    payload = {
        "type": "page",
        "title": title,
        "space": {"key": SPACE_KEY},
        "body": {
            "atlas_doc_format": {
                "value": make_adf(body_markdown),
                "representation": "atlas_doc_format",
            }
        },
    }
    return ccp.api_request("POST", "content", payload)


# ── Per-file publish ───────────────────────────────────────────────────────────


def title_for_file(filename):
    """michael-seaman.md → 'Outbox · <APPROVER_NAME>'
    _vendor.md          → 'Outbox · _Vendor'"""
    stem = Path(filename).stem
    if stem.startswith("_"):
        label = "_" + stem[1:].replace("-", " ").title()
    else:
        label = stem.replace("-", " ").title()
    return f"Outbox · {label}"


def build_body(filename, source_text):
    """Strip the existing H1 from the outbox file so the page title isn't duplicated.
    Add a small auto-published banner."""
    title = title_for_file(filename)
    lines = source_text.splitlines()
    # Drop leading H1 if present
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
    # Trim leading blanks
    while lines and not lines[0].strip():
        lines = lines[1:]
    body = "\n".join(lines)
    header = (
        f"# {title}\n\n"
        f"_Auto-published from `planner/outbox/{filename}`. Direction set in "
        f"meetings goes straight into the Jira ticket — click **💬 Comment on "
        f"Jira** under each card. This page is overwritten on the next "
        f"publish; nothing typed here is captured._\n\n"
    )
    return header + body


def publish_file(path, page_id, parent_id, dry_run=False):
    title = title_for_file(path.name)
    body = build_body(path.name, path.read_text(encoding="utf-8"))

    if dry_run:
        adf = ccp.md_to_adf(body)
        action = "update" if page_id else "create"
        print(f"   [dry-run] would {action} '{title}' ({len(adf['content'])} ADF nodes)")
        return page_id or f"<new-{path.stem}>"

    if page_id and fetch_page(page_id):
        res = update_page(page_id, title, body)
        print(f"   ✓ updated v{res['version']['number']}")
        return page_id

    res = create_page(title, parent_id, body)
    new_id = res["id"]
    print(f"   ✓ created → {new_id}")
    return new_id


# ── Index file ─────────────────────────────────────────────────────────────────


def write_index(mapping, files):
    lines = [
        "# Outbox · Confluence Index",
        "",
        "Confluence URLs for each outbox file. Share the relevant link with the",
        "stakeholder when following up. Regenerated by `scripts/outbox_publish.py`.",
        "",
        f"**Parent:** [WWeeks Outbox]({page_url(mapping['_parents']['outbox'], 'WWeeks+Outbox')})",
        "",
        "| File | Confluence Page |",
        "| --- | --- |",
    ]
    for f in files:
        page_id = mapping["files"].get(f.name)
        if not page_id:
            lines.append(f"| `{f.name}` | _(not published)_ |")
            continue
        title = title_for_file(f.name)
        url = page_url(page_id, title.replace("·", "").replace("  ", " "))
        lines.append(f"| `{f.name}` | [{title}]({url}) |")
    lines.append("")
    INDEX_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n📇 Wrote {INDEX_FILE.relative_to(REPO_ROOT)}")


# ── Main ───────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--wweeks-parent-id",
        help="Use this existing page as the WWeeks parent instead of creating one.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Show actions without calling Confluence."
    )
    args = parser.parse_args()

    ccp.load_env()

    if not OUTBOX_DIR.exists():
        fail(
            f"Outbox directory does not exist: {OUTBOX_DIR}",
            causes=["planner/outbox/ has not been created yet",
                    "Running from wrong directory"],
            try_=["mkdir -p planner/outbox",
                  "python3 scripts/outbox_refresh.py  # generate outbox files first"],
        )

    mapping = load_mapping()
    if args.wweeks_parent_id:
        mapping["_parents"]["wweeks"] = args.wweeks_parent_id

    # Bootstrap parents
    print("── Parent pages " + "─" * 50)
    wweeks_id = ensure_parent(mapping, "wweeks", "WWeeks", WWEEKS_INTRO, dry_run=args.dry_run)
    outbox_id = ensure_parent(
        mapping, "outbox", "WWeeks Outbox", OUTBOX_INTRO,
        parent_id=wweeks_id, dry_run=args.dry_run,
    )
    if not args.dry_run:
        save_mapping(mapping)

    # Publish per-file pages
    files = sorted(p for p in OUTBOX_DIR.glob("*.md") if p.name != "INDEX.md")
    if not files:
        print("\n⚠️  No outbox markdown files found.")
        return

    print(f"\n── Stakeholder pages ({len(files)}) " + "─" * 35)
    for f in files:
        print(f"📄 {f.name}")
        page_id = mapping["files"].get(f.name)
        new_id = publish_file(f, page_id, outbox_id, dry_run=args.dry_run)
        if not args.dry_run and new_id and not str(new_id).startswith("<new-"):
            mapping["files"][f.name] = new_id
            save_mapping(mapping)

    # Write index
    if not args.dry_run:
        write_index(mapping, files)

    print(f"\n✅ Done. WWeeks Outbox: {page_url(outbox_id, 'WWeeks+Outbox')}")


if __name__ == "__main__":
    main()
