baseURL = "http://localhost:1314/"
defaultContentLanguage = "en"
title = "Journal"
publishDir = "public"
contentDir = "content"
layoutDir = "layouts"
archetypeDir = "archetypes"
staticDir = "static"
dataDir = "data"

disableKinds = ["taxonomy", "term", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
